#!/bin/bash
# mkdir -p ~/root
docker run -it --name Abathur -v ~/root:/root -p 3000:3000 python:2-slim bash@@
# dans le container
# pip install Flask
# apt-get update
# apt-get install -y vim
# dans vim
# créer app.py dans ~/root
# from flask import Flask
# app = Flask(__name__)
# @app.route('/')
# def index():
#     return ('<!DOCTYPE html><html><head><title></title></head><body><h1>Hello World</h1></body></html>')

# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port="3000")

# # puis lancer
# python /root/app.py
